version: "3"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_USER_MANAGEMENT_DISABLED=true  # <--- disable user setup
    volumes:
      - ./n8n-data:/home/node/.n8n
